name: Auto-approve my own PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read        
  pull-requests: write  

jobs:
  self-approve:
    if: github.actor == 'katseitz'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Approve pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });
