name: Auto-approve my own PRs
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  self-approve:
    if: github.actor == 'katseitz'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.payload.pull_request.number
            await github.rest.pulls.createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE'
            })
