name: Auto-approve my own PRs
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  self-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'katseitz'
    permissions:
      pull-requests: write
    steps:
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

